root - INFO - API created
root - INFO - Processing tweet id 1295624620251308032
root - INFO - Processing tweet id 1295624621127946240
root - ERROR - Error on liking
Traceback (most recent call last):
  File "c:\Users\Josh\Desktop\twitterbots\stream.py", line 31, in on_status
    tweet.favorite()
  File "C:\Users\Josh\Desktop\twitterbots\twitterenv\lib\site-packages\tweepy\models.py", line 127, in favorite
    return self._api.create_favorite(self.id)
  File "C:\Users\Josh\Desktop\twitterbots\twitterenv\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\Josh\Desktop\twitterbots\twitterenv\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 139, 'message': 'You have already favorited this status.'}]
root - INFO - Processing tweet id 1295624621966815233
root - INFO - Processing tweet id 1295624623183114240
root - INFO - Processing tweet id 1295624624386932737
